name: desktop-report-build
description: Desktop report build
inputs:
  token:
    description: Github token
    required: true
  statuses:
    description: Statuses of the jobs
    required: true
  attempt:
    description: Attempt number
    required: true

runs:
  using: node20
  main: build/main.js
